### ISSUE TITLE
Possible inaccurate genetics scenario

### ISSUE THREAD

**Issue by bkuhl** [Lenart12/Rust-Genetics-Calculator#1]
I was tinkering with genetics last night and came across this scenario.  Based on my understanding, the 2nd to last column on the available seeds would either produce:

  - `W` because it's dominant and there's not enough of any other green to overtake it
  - `33% chance of each green` because combined they overtake the `W` but there's no dominant one

<img width="698" alt="Screen Shot 2021-02-11 at 12 43 56 PM" src="https://user-images.githubusercontent.com/524933/107676205-df139a80-6c66-11eb-8ae7-b934aa03d12b.png">

Is it an error that this shows it keeping the original `G` gene?

**Comment by bkuhl** [comment]
I _love_ this tool by the way, thank you for this!

**Comment by Lenart12** [comment]
Thanks for reporting, I will take a look... very strange

**Comment by Lenart12** [comment]
Oh... I know whats wrong :D Its working fine, there is no best crosbreeding output, the seed GGHGGH is already the best possible you have; all child genes would be of lesser value with your current (or maybe any) slider settings.

**Comment by Lenart12** [comment]
I will implement multi-level gene searching maybe it would find better combinations.
